const app=document.querySelector('#app');let questions=[],answers=[],index=0,finished=false;const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function home(){app.innerHTML=`<section class="intro"><div class="intro-main"><span class="eyebrow">业务能力 · 随机测验</span><h1>把业务知识，变成日常底气。</h1><p>岗位名词、销售分析、物流知识交叉出题。<br>用自己的话填写答案，交卷后查看成绩。</p><div class="stats"><div><b>20 题</b><span>每套随机抽取</span></div><div><b>≥ 80%</b><span>相似度判对</span></div><div><b>≥ 18 题</b><span>答对即合格</span></div></div><button id="start" class="wide">开始考试</button><p class="note">不限时 · 每套题目不重复 · 无需登录</p></div><div class="intro-side"><div class="big">${BANK.length}<small> 道</small></div><div><h3>三类业务题库</h3><p>岗位名词 / 销售分析 / 物流知识</p><span class="pill">每次重新抽题</span></div></div></section><p class="note below">题库依据提供的培训资料整理，同义重复词条合并。评分为文字相似度：忽略大小写、常见标点并替换部分同义词，再计算编辑距离；语义相同但措辞差异较大仍可能失分。公式、数字和时段请准确填写。此版本适用于学习自测。</p>`;document.querySelector('#start').onclick=start;}
function start(){questions=makeExam(BANK);answers=Array(20).fill('');index=0;finished=false;save();render();}
function save(){try{sessionStorage.setItem('exam-v1',JSON.stringify({questions,answers,index,finished}));}catch{}}
function render(){const q=questions[index],n=answers.filter(a=>a.trim()).length;app.innerHTML=`<div class="exam"><section class="card"><div class="topline"><span>业务知识测验</span><span>第 ${index+1} / 20 题</span></div><div class="progress"><span style="width:${n*5}%"></span></div><span class="pill">${q.category}</span><h2 class="question">请解释「${esc(q.term)}」</h2><label for="answer">你的答案</label><textarea id="answer" maxlength="2000" placeholder="请输入名词含义；指标类题目请写出计算公式。">${esc(answers[index])}</textarea><div class="topline"><span>相似度达到 80% 判为答对</span><span id="length">${answers[index].length} / 2000</span></div><div class="actions"><button id="prev" class="outline" ${index===0?'disabled':''}>上一题</button><button id="next">${index===19?'检查并交卷':'下一题'}</button></div></section><aside class="card"><h3>答题卡</h3><p id="count">已作答 ${n} / 20 题</p><div class="numbers">${questions.map((_,i)=>`<button aria-label="跳转第${i+1}题" class="${answers[i].trim()?'filled ':''}${i===index?'active':''}" data-i="${i}">${i+1}</button>`).join('')}</div><button class="outline wide" id="submit">交卷评分</button><p class="note">可随时返回修改。<br>交卷后公布标准答案。</p></aside></div>`;document.querySelector('#answer').oninput=e=>{answers[index]=e.target.value;save();document.querySelector('#length').textContent=e.target.value.length+' / 2000';document.querySelector('#count').textContent=`已作答 ${answers.filter(a=>a.trim()).length} / 20 题`;document.querySelector('.progress span').style.width=answers.filter(a=>a.trim()).length*5+'%';};document.querySelector('#prev').onclick=()=>go(index-1);document.querySelector('#next').onclick=()=>index===19?askSubmit():go(index+1);document.querySelector('#submit').onclick=askSubmit;document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>go(Number(b.dataset.i)));}
function go(i){index=i;save();render();window.scrollTo({top:0,behavior:'smooth'});document.querySelector('#answer').focus({preventScroll:true});}
function askSubmit(){const n=answers.filter(a=>!a.trim()).length;document.querySelector('#confirmText').textContent=n?`还有 ${n} 题未作答，空白答案将计为答错。`:'20 题已全部作答，交卷后将公布成绩和标准答案。';document.querySelector('#confirm').showModal();}
function result(){finished=true;save();const scores=questions.map((q,i)=>similarity(answers[i],q.answer)),correct=scores.filter(s=>s>=80).length;app.innerHTML=`<section class="card result"><span class="eyebrow">考试结果</span><h1 class="${correct>=18?'pass':'fail'}">${correct>=18?'恭喜，考试合格':'未合格，再接再厉'}</h1><strong>${correct*5}<small style="font-size:20px"> 分</small></strong><p>答对 ${correct} / 20 题 · 正确率 ${correct*5}%<br>合格标准：答对至少 18 题（90%）</p><button id="retry">重新抽题考试</button></section><h2>逐题解析</h2><p class="note">相似度显示保留一位小数，判定使用未四舍五入的原始值。标准答案依据提供的培训资料整理。</p>${questions.map((q,i)=>`<article class="card review"><div class="topline"><h3>${i+1}. ${esc(q.term)}</h3><span class="score ${scores[i]>=80?'pass':'fail'}">${scores[i]>=80?'答对':'答错'} · ${Math.floor(scores[i]*10)/10}%</span></div><label>你的答案</label><p>${esc(answers[i]||'（未作答）')}</p><label>标准答案</label><p>${esc(q.answer)}</p></article>`).join('')}`;document.querySelector('#retry').onclick=start;window.scrollTo(0,0);}
document.querySelector('#cancelSubmit').onclick=()=>document.querySelector('#confirm').close();document.querySelector('#confirmSubmit').onclick=()=>{document.querySelector('#confirm').close();result();};document.querySelector('#share').onclick=()=>document.querySelector('#sharing').showModal();document.querySelector('.close').onclick=()=>document.querySelector('#sharing').close();document.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+location.pathname);document.querySelector('#shareStatus').textContent='链接已复制，可以发送给同事。';}catch{document.querySelector('#shareStatus').textContent=location.origin+location.pathname;}};
try{const s=JSON.parse(sessionStorage.getItem('exam-v1'));if(s&&s.questions?.length===20&&s.answers?.length===20){({questions,answers,index,finished}=s);finished?result():render();}else home();}catch{home();}
